# Generated by Django 5.1.1 on 2024-11-28 23:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DuoMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_username', models.CharField(help_text='The Spotify username of the sender.', max_length=255)),
                ('receiver_username', models.CharField(help_text='The Spotify username of the receiver.', max_length=255)),
                ('wrap_data', models.JSONField(help_text='The combined wrap data for the duo wrap.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the duo message was created.')),
            ],
        ),
        migrations.CreateModel(
            name='Wrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_username', models.CharField(max_length=255)),
                ('product', models.CharField(default='Unknown', max_length=50)),
                ('top_song', models.CharField(blank=True, max_length=255, null=True)),
                ('top_artists', models.JSONField(blank=True, null=True)),
                ('listened_genre', models.CharField(blank=True, max_length=255, null=True)),
                ('top_album', models.CharField(blank=True, max_length=255, null=True)),
                ('listened_hours', models.FloatField(blank=True, null=True)),
                ('most_listened_artist', models.JSONField(blank=True, null=True)),
                ('top_artist_tracks', models.JSONField(blank=True, null=True)),
                ('top_artist_song', models.CharField(blank=True, max_length=255, null=True)),
                ('special_message', models.TextField(blank=True, null=True)),
                ('gemini_recommendations', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_range', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DuoWrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('wrap1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duowraps_as_first', to='wrap_app.wrap')),
                ('wrap2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duowraps_as_second', to='wrap_app.wrap')),
            ],
        ),
    ]
