# Generated by Django 5.1.1 on 2024-11-29 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrap_app', '0001_initial'),
    ]

    operations = [
    ]
