# Generated by Django 5.1.1 on 2024-11-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrap_app', '0002_auto_20241129_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wrap',
            name='time_range',
        ),
        migrations.AlterField(
            model_name='wrap',
            name='top_song',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
    ]
