# Generated by Django 5.1.1 on 2024-11-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrap_app', '0003_remove_wrap_time_range_alter_wrap_top_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrap',
            name='time_range',
            field=models.CharField(max_length=255, blank=True, null=True),
        ),
    ]
