# Generated by Django 5.1.1 on 2024-11-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrap_app', '0004_auto_20241130_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wrap',
            name='time_range',
        ),
        migrations.AlterField(
            model_name='wrap',
            name='top_album',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
    ]
